volumes:
  # docker volume create chatbot-redis-data
  chatbot-redis-data:
    driver: local

  # docker volume create chatbot-mongodb-data
  chatbot-mongodb-data:
    driver: local

  # docker volume create chatbot-qdrant-data
  chatbot-qdrant-data:
    driver: local

  # docker volume create chatbot-mino-data
  chatbot-mino-data:
    driver: local

  # docker volume create chatbot-ollama-model
  chatbot-ollama-model:
    driver: local

  # docker volume create chatbot-celery-cache
  chatbot-celery-cache:
    driver: local
 
networks:
  # docker network create chatbot-networks
  chatbot-networks:
    driver: bridge

services:
  # Redis
  # docker run -d --name chatbot-redis \
  # --network chatbot-networks -p 6379:6379 -v chatbot-redis-data:/data \
  # redis/redis-stack-server:latest
  chatbot-redis:
    image: redis/redis-stack-server:latest
    container_name: chatbot-redis
    ports:
      - "6379:6379"
    volumes:
      - chatbot-redis-data:/data
    networks:
      - chatbot-networks

  # Celery
  # docker build -t chatbot-celery-worker ./celery
  # docker run -d --name chatbot-celery-worker --gpus all \
  # --network chatbot-networks -e REDIS_HOST=chatbot-redis \
  # chatbot-celery-worker
  chatbot-celery:
    build: ./celery
    image: chatbot-celery-worker
    container_name: chatbot-celery
    networks:
      - chatbot-networks
    environment:
      - REDIS_HOST=chatbot-redis
      - HF_HOME=/cache/huggingface
    volumes:
      - chatbot-celery-cache:/cache/huggingface
    depends_on:
      - chatbot-redis
    # GPU support. If you don't have GPU, remove the following lines
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  # MongoDB
  # docker run -d --name chatbot-mongodb \
  # --network chatbot-networks -p 27017:27017 -v chatbot-mongodb-data:/data/db \
  # mongodb/mongodb-community-server:latest
  chatbot-mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: chatbot-mongodb
    ports:
      - "27017:27017"
    volumes:
      - chatbot-mongodb-data:/data/db
      - ./docker/mongodb-config:/data/configdb
    networks:
      - chatbot-networks

  # Minio
  # docker run -d --name chatbot-minio \
  # --network chatbot-networks -p 9000:9000 -p 9001:9001 -v chatbot-mino-data:/data \
  # -e MINIO_ROOT_USER=admin -e MINIO_ROOT_PASSWORD=admin123 minio/minio \
  # server --console-address ":9001" /data
  chatbot-minio:
    image: minio/minio
    container_name: chatbot-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - chatbot-mino-data:/data
    environment:
      MINIO_ROOT_USER: adminuser
      MINIO_ROOT_PASSWORD: adminuser
    networks:
      - chatbot-networks
    command: server --console-address ":9001" /data

  # Qdrant
  # docker run -d --name chatbot-qdrant \
  # --network chatbot-networks -p 6333:6333 -p 6334:6334 -v chatbot-qdrant-data:/qdrant/storage \
  # qdrant/qdrant:latest
  chatbot-qdrant:
    image: qdrant/qdrant:latest
    container_name: chatbot-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - chatbot-qdrant-data:/qdrant/storage
    networks:
      - chatbot-networks

  # Ollama
  # docker run -d --name chatbot-ollama \
  # --network chatbot-networks -p 11434:11434 ollama/ollama:latest
  # docker exec ollama ollama run llama3.2
  chatbot-ollama:
    image: ollama/ollama:latest
    container_name: chatbot-ollama
    ports:
      - "11434:11434"
    volumes:
      - chatbot-ollama-model:/root/.ollama
      - ./docker/ollama-entrypoint.sh:/entrypoint.sh
    networks:
      - chatbot-networks
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    # GPU support. If you don't have GPU, remove the following lines
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  # App Services
  # docker build -t chatbot-app-image .
  # docker run -d --name chatbot-app --gpus all \
  # --network chatbot-networks -p 7860:7860 chatbot-app-image
  chatbot-app:
    build: .
    image: chatbot-app-image
    container_name: chatbot-app
    ports:
      - "7860:7860"
    networks:
      - chatbot-networks
    env_file:
      - .env
    environment:
      - REDIS_HOST=chatbot-redis
      - MONGODB_HOST=chatbot-mongodb
      - QDRANT_HOST=chatbot-qdrant
      - MINIO_HOST=chatbot-minio
      - LLM_OLLAMA_HOST=chatbot-ollama
      - MINIO_ACCESS_KEY=adminuser
      - MINIO_SECRET_KEY=adminuser
    depends_on:
      - chatbot-celery
      - chatbot-mongodb
      - chatbot-qdrant
      - chatbot-minio
      - chatbot-ollama
    # GPU support. If you don't have GPU, remove the following lines
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]